### ISSUE TITLE
HtmlEntities.decode("&nbsp;") == " " returns false?

### ISSUE THREAD

**Issue by ibarrae** [martinsvalin/html_entities#24]
Hey folks, thanks for the awesome library!.

A few minutes ago I just updated the version from `0.4.0` to `0.5.1` and I found out the following odd behavior.
``` elixir
iex(10)> true = HtmlEntities.decode("&nbsp;") == " " 
** (MatchError) no match of right hand side value: false
```

If you only decode the value, it returns " ".
``` elixir
iex(10)> HtmlEntities.decode("&nbsp;")               
" "
```
I wonder if this is a bug because it didn't have this behavior on version `0.4.0` :thinking:

**Comment by martinsvalin** [comment]
Hi. What is the codepoint of the whitespace you are comparing to here? I believe the behaviour you see is correct.
The `&nbsp;` entity is for a non-breaking space, codepoint 160, while a normal space, i.e. what you get from hitting the spacebar, is codepoint 32. 

There was a long-standing bug previously, where my editor "helpfully" converted non-breaking spaces to regular spaces on save. I copied the entities from wikipedia and did not notice the difference between ' ' and ' ' (codepoints 32 and 160 display identically). Since I translated using the literal character in that list, it came out wrong. I realized my error and fixed the entities list in d05ec7c, and decided to also use the numerical codepoint in translation. It'll be less susceptible to mistakes of this kind. This fix was released in 0.5.1.

Sorry 'bout the bug! =)
